@echo off
echo Verificando la existencia del ambiente virtual...
if not exist env (
  echo Creando el ambiente virtual...
  python -m venv env
)
echo Activando el ambiente virtual...
call mi_entorno\Scripts\activate
echo Instalando las dependencias...
pip install -r requirements.txt
echo Ejecutando la aplicación de Streamlit...
streamlit run index.py
echo Desactivando el ambiente virtual...
deactivate